### PR TITLE
fetch options per amiel - https://github.com/Driversnote-Dev/guard-er…

### PR DESCRIPTION
**Pull request by bmcanelly**
…b_lint/issues/1

### CODE REVIEW

**Comment by mathiashsteffensen** [comment]
Thank you for contributing, changes look good to me 👍

**Comment by amiel** [comment]
Thank you for fixing this!

**Comment by inkstak** [comment]
Hi ! Did you plan to release this ?
Thanks in advance.

**Comment by mathiashsteffensen** [comment]
> Hi ! Did you plan to release this ? Thanks in advance.

This small project is only distributed through Git, so any new merge into master is basically a release.

If you run `bundle update guard-erb_lint` in your project directory it should update to the latest Git revision.

**Pull request merged**
